[project]
name = "pruebas-prefect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.3",
    "prefect>=3.6.9",
    "python-dotenv>=1.2.1",
    "requests>=2.32.0",
    "scikit-learn>=1.6.1",
    "wandb>=0.25.1",
]
